### PR TITLE
feat: implement EnhanceDocs Search

### PR DESCRIPTION
**Pull request by Alw3ys**
As demand from @raulraja to implement EnhanceDocs on Arrow Documentation.

What does this PR includes?
- Implementation of EnhanceDocs Search Bar on the site (see screenshoot below)
- Build automation: Implement new build and update every time a new deployment is pushed.

TODO @raulraja:
Get secret at https://app.enhancedocs.com/settings/api-keys and create github action secret with variable name `ENHANCEDOCS_API_KEY` with secret from https://github.com/arrow-kt/arrow-website/settings/secrets/actions/new

Preview:
Screenshot 2023-05-01 at 13 23 32

### CODE REVIEW

**Comment by raulraja** [comment]
@franciscodr Could you help with the setup?
> Get secret at https://app.enhancedocs.com/settings/api-keys and create github action secret with variable name ENHANCEDOCS_API_KEY with secret from https://github.com/arrow-kt/arrow-website/settings/secrets/actions/new

@Alw3ys also mentioned that there is a Slack bot that we can connect to the AI assistant to use it from slack as well

**Comment by Alw3ys** [comment]
Hey @raulraja , any blockers?

**Comment by nomisRev** [comment]
@Alw3ys, I ran into a white page after trying to get a secret from https://app.enhancedocs.com/settings/api-keys. This is currently blocking me to add the secret to the repo. This happened after trying to login in through the Github login.

**Comment by Alw3ys** [comment]
Um, interesting, I think you must sign up. I don't see that you have created an account. but I will look into this so messaging is more clear

**Comment by franciscodr** [comment]
Hi @Alw3ys, sorry for the late response. Thanks for bringing this proposal to our website. It looks great! I would like to ask if there's another way to integrate EnhancedDocs into our website rather than replacing the current search engine. We're considering having a complementary feature like a chat prompt where the user can interact with EnhancedDocs while maintaining the current search component in the top bar.

**Comment by Alw3ys** [comment]
Updated the PR: here's a screenshot:
Screenshot 2023-05-10 at 19 22 46

**Review by calvellido — APPROVED** [review]
It looks great @Alw3ys, thanks for updating the PR :raised_hands:

**Comment by Alw3ys** [comment]
Awesome, just make sure to add the API key to the github action secrets as I mention on my first commit before merge, otherwise the build will fail with a 403, otherwise ready to merge :)

**Comment by franciscodr** [comment]
I already added the API key in the repo's secrets. The AI assistant looks great, @Alw3ys!

**Review by franciscodr — APPROVED** [review]

**Comment by Alw3ys** [comment]
Sure you need to find a way to download it and upload with the CLI, but if you wait a week or so we will release our new version of managed build and this can be done. will keep you posted!

**Comment by Alw3ys** [comment]
Hey, I'm soo sorry I noticed the build failed because it caught us in the middle of a deployment. would you mind retrying again? Sorry!!!

**Pull request merged**
